- context:
    name: "crispr12a"
    seq: "2HKVSTQAYELWEKNSIAIKVKDLKEDEAKKFQGIAWLVKRAINYAGNADANKPLIANEQAEYNRSDYFIGDSNKVPSILFDVDTRGTISNRMQLMLSMLAMFSSYFAKDSQECLLARIDGQQYNIGYKNFLEKYASTLCVEEWDFVNNKKPNRFIRIRNGYSYLKWKKIYDADTRSFNKYDLAFEFLDEEPVYMIRDFSSIFKKSDAISTYKTKLLNVFGTSPDIKSTLWAPIYFIFGNQTSMSKFSEFKNTIQYGKLAGGTACPNSKKDVMYNLKDILMKEFKQYVQKEVKVRSNKFGSNLDELAIVADYKEVLECIKHVVQSIYGAKLEKINEISTWNQRAEFREKEKKDLLSHYDTKIRIGNFNNIIENLSYQEVINGKGDVVVIYLLNREGRAIGIVYPNDDHKLLVRVETNIKFINKPCKNIAIPIHLEYQDESFRKDKYVDYSLTTTKKPNDPNKNAIPSNAPHVVLEEKKLSARRMFLEAGGSLRIQGHNNEDFLLKFYMTHLNPTGHSKDSFDKNYIQFMYLKGEEVLKDVEKKSASEFSVKYGQEEVERYFGAIDKYKETESFNFDYANSWKPYRSISDKFFDILKHCDNLNFMDGKKFTGNKYIKQIDESPNYYAMWKKSFFVKPLMKNPGPLLKYNIKEYNGNVDDKDIKQLCKAYKKDMIALYYKSGYRLITARYDTEKDKDWGGMFQPNQFYLKFKDKSYPKQTVYNRIADYIHDVKLLIDYALVFDGYFSEDRNTEKGEGFFAKIYNEFSKVSDLLDKMIAVVADNKKLSKELVFDADFLKESSGYVKYIEDVKQIIIEKLKEVVSLDADAYEQLQELSFSGIKKFSKRRDDEYKETVVAKKKLHIDDYEANWKDRIVNWEGFIRKSITSIAPGNKVFIGASSYEDFNKFLKELKKISSFIESNKNLTNRFVELVEEDSTYGRGYFSLSERDSLVQKYLPKFKPLKQKTKQNYLNIYENLGKIKEGSETVFGGIIANYVRIGEQTLVFNFFEGEFFDEVDYDSNLIKEKIEQVEHKDFIADVKEFIDMNSIYRTLNENICRFAISTSKAEESFMNERNRFFGTFATTFGNFSNVLAIEDKDDLFEPLITEIIDKKFLSKYGENGKFAKAIEKRLNIELNELEKNEKETRTKKRFLSIYNNLNKLKISHLVDNIFSLYYRDLLKKVGKYDEARKEDEVLLRKNDINEQTKG"

  num_samples: 10000
  batch_size: 128
  do_sample: true
  temperature: 0.5
  top_p: 0.5
  top_k: 0
  repetition_penalty: 1.05

- context:
    name: "crispr12a"
    seq: "2HKVSTQAYELWEKNSIAIKVKDLKEDEAKKFQGIAWLVKRAINYAGNADANKPLIANEQAEYNRSDYFIGDSNKVPSILFDVDTRGTISNRMQLMLSMLAMFSSYFAKDSQECLLARIDGQQYNIGYKNFLEKYASTLCVEEWDFVNNKKPNRFIRIRNGYSYLKWKKIYDADTRSFNKYDLAFEFLDEEPVYMIRDFSSIFKKSDAISTYKTKLLNVFGTSPDIKSTLWAPIYFIFGNQTSMSKFSEFKNTIQYGKLAGGTACPNSKKDVMYNLKDILMKEFKQYVQKEVKVRSNKFGSNLDELAIVADYKEVLECIKHVVQSIYGAKLEKINEISTWNQRAEFREKEKKDLLSHYDTKIRIGNFNNIIENLSYQEVINGKGDVVVIYLLNREGRAIGIVYPNDDHKLLVRVETNIKFINKPCKNIAIPIHLEYQDESFRKDKYVDYSLTTTKKPNDPNKNAIPSNAPHVVLEEKKLSARRMFLEAGGSLRIQGHNNEDFLLKFYMTHLNPTGHSKDSFDKNYIQFMYLKGEEVLKDVEKKSASEFSVKYGQEEVERYFGAIDKYKETESFNFDYANSWKPYRSISDKFFDILKHCDNLNFMDGKKFTGNKYIKQIDESPNYYAMWKKSFFVKPLMKNPGPLLKYNIKEYNGNVDDKDIKQLCKAYKKDMIALYYKSGYRLITARYDTEKDKDWGGMFQPNQFYLKFKDKSYPKQTVYNRIADYIHDVKLLIDYALVFDGYFSEDRNTEKGEGFFAKIYNEFSKVSDLLDKMIAVVADNKKLSKELVFDADFLKESSGYVKYIEDVKQIIIEKLKEVVSLDADAYEQLQELSFSGIKKFSKRRDDEYKETVVAKKKLHIDDYEANWKDRIVNWEGFIRKSITSIAPGNKVFIGASSYEDFNKFLKELKKISSFIESNKNLTNRFVELVEEDSTYGRGYFSLSERDSLVQKYLPKFKPLKQKTKQNYLNIYENLGKIKEGSETVFGGIIANYVRIGEQTLVFNFFEGEFFDEVDYDSNLIKEKIEQVEHKDFIADVKEFIDMNSIYRTLNENICRFAISTSKAEESFMNERNRFFGTFATTFGNFSNVLAIEDKDDLFEPLITEIIDKKFLSKYGENGKFAKAIEKRLNIELNELEKNEKETRTKKRFLSIYNNLNKLKISHLVDNIFSLYYRDLLKKVGKYDEARKEDEVLLRKNDINEQTKG"

  num_samples: 10000
  batch_size: 128
  do_sample: true
  temperature: 0.5
  top_p: 0.95
  top_k: 0
  repetition_penalty: 1.05

- context:
    name: "crispr12a"
    seq: "2HKVSTQAYELWEKNSIAIKVKDLKEDEAKKFQGIAWLVKRAINYAGNADANKPLIANEQAEYNRSDYFIGDSNKVPSILFDVDTRGTISNRMQLMLSMLAMFSSYFAKDSQECLLARIDGQQYNIGYKNFLEKYASTLCVEEWDFVNNKKPNRFIRIRNGYSYLKWKKIYDADTRSFNKYDLAFEFLDEEPVYMIRDFSSIFKKSDAISTYKTKLLNVFGTSPDIKSTLWAPIYFIFGNQTSMSKFSEFKNTIQYGKLAGGTACPNSKKDVMYNLKDILMKEFKQYVQKEVKVRSNKFGSNLDELAIVADYKEVLECIKHVVQSIYGAKLEKINEISTWNQRAEFREKEKKDLLSHYDTKIRIGNFNNIIENLSYQEVINGKGDVVVIYLLNREGRAIGIVYPNDDHKLLVRVETNIKFINKPCKNIAIPIHLEYQDESFRKDKYVDYSLTTTKKPNDPNKNAIPSNAPHVVLEEKKLSARRMFLEAGGSLRIQGHNNEDFLLKFYMTHLNPTGHSKDSFDKNYIQFMYLKGEEVLKDVEKKSASEFSVKYGQEEVERYFGAIDKYKETESFNFDYANSWKPYRSISDKFFDILKHCDNLNFMDGKKFTGNKYIKQIDESPNYYAMWKKSFFVKPLMKNPGPLLKYNIKEYNGNVDDKDIKQLCKAYKKDMIALYYKSGYRLITARYDTEKDKDWGGMFQPNQFYLKFKDKSYPKQTVYNRIADYIHDVKLLIDYALVFDGYFSEDRNTEKGEGFFAKIYNEFSKVSDLLDKMIAVVADNKKLSKELVFDADFLKESSGYVKYIEDVKQIIIEKLKEVVSLDADAYEQLQELSFSGIKKFSKRRDDEYKETVVAKKKLHIDDYEANWKDRIVNWEGFIRKSITSIAPGNKVFIGASSYEDFNKFLKELKKISSFIESNKNLTNRFVELVEEDSTYGRGYFSLSERDSLVQKYLPKFKPLKQKTKQNYLNIYENLGKIKEGSETVFGGIIANYVRIGEQTLVFNFFEGEFFDEVDYDSNLIKEKIEQVEHKDFIADVKEFIDMNSIYRTLNENICRFAISTSKAEESFMNERNRFFGTFATTFGNFSNVLAIEDKDDLFEPLITEIIDKKFLSKYGENGKFAKAIEKRLNIELNELEKNEKETRTKKRFLSIYNNLNKLKISHLVDNIFSLYYRDLLKKVGKYDEARKEDEVLLRKNDINEQTKG"

  num_samples: 10000
  batch_size: 128
  do_sample: true
  temperature: 0.7
  top_p: 0.5
  top_k: 0
  repetition_penalty: 1.05

- context:
    name: "crispr12a"
    seq: "2HKVSTQAYELWEKNSIAIKVKDLKEDEAKKFQGIAWLVKRAINYAGNADANKPLIANEQAEYNRSDYFIGDSNKVPSILFDVDTRGTISNRMQLMLSMLAMFSSYFAKDSQECLLARIDGQQYNIGYKNFLEKYASTLCVEEWDFVNNKKPNRFIRIRNGYSYLKWKKIYDADTRSFNKYDLAFEFLDEEPVYMIRDFSSIFKKSDAISTYKTKLLNVFGTSPDIKSTLWAPIYFIFGNQTSMSKFSEFKNTIQYGKLAGGTACPNSKKDVMYNLKDILMKEFKQYVQKEVKVRSNKFGSNLDELAIVADYKEVLECIKHVVQSIYGAKLEKINEISTWNQRAEFREKEKKDLLSHYDTKIRIGNFNNIIENLSYQEVINGKGDVVVIYLLNREGRAIGIVYPNDDHKLLVRVETNIKFINKPCKNIAIPIHLEYQDESFRKDKYVDYSLTTTKKPNDPNKNAIPSNAPHVVLEEKKLSARRMFLEAGGSLRIQGHNNEDFLLKFYMTHLNPTGHSKDSFDKNYIQFMYLKGEEVLKDVEKKSASEFSVKYGQEEVERYFGAIDKYKETESFNFDYANSWKPYRSISDKFFDILKHCDNLNFMDGKKFTGNKYIKQIDESPNYYAMWKKSFFVKPLMKNPGPLLKYNIKEYNGNVDDKDIKQLCKAYKKDMIALYYKSGYRLITARYDTEKDKDWGGMFQPNQFYLKFKDKSYPKQTVYNRIADYIHDVKLLIDYALVFDGYFSEDRNTEKGEGFFAKIYNEFSKVSDLLDKMIAVVADNKKLSKELVFDADFLKESSGYVKYIEDVKQIIIEKLKEVVSLDADAYEQLQELSFSGIKKFSKRRDDEYKETVVAKKKLHIDDYEANWKDRIVNWEGFIRKSITSIAPGNKVFIGASSYEDFNKFLKELKKISSFIESNKNLTNRFVELVEEDSTYGRGYFSLSERDSLVQKYLPKFKPLKQKTKQNYLNIYENLGKIKEGSETVFGGIIANYVRIGEQTLVFNFFEGEFFDEVDYDSNLIKEKIEQVEHKDFIADVKEFIDMNSIYRTLNENICRFAISTSKAEESFMNERNRFFGTFATTFGNFSNVLAIEDKDDLFEPLITEIIDKKFLSKYGENGKFAKAIEKRLNIELNELEKNEKETRTKKRFLSIYNNLNKLKISHLVDNIFSLYYRDLLKKVGKYDEARKEDEVLLRKNDINEQTKG"

  num_samples: 10000
  batch_size: 128
  do_sample: true
  temperature: 0.7
  top_p: 0.95
  top_k: 0
  repetition_penalty: 1.05

- context:
    name: "crispr12a"
    seq: "2HKVSTQAYELWEKNSIAIKVKDLKEDEAKKFQGIAWLVKRAINYAGNADANKPLIANEQAEYNRSDYFIGDSNKVPSILFDVDTRGTISNRMQLMLSMLAMFSSYFAKDSQECLLARIDGQQYNIGYKNFLEKYASTLCVEEWDFVNNKKPNRFIRIRNGYSYLKWKKIYDADTRSFNKYDLAFEFLDEEPVYMIRDFSSIFKKSDAISTYKTKLLNVFGTSPDIKSTLWAPIYFIFGNQTSMSKFSEFKNTIQYGKLAGGTACPNSKKDVMYNLKDILMKEFKQYVQKEVKVRSNKFGSNLDELAIVADYKEVLECIKHVVQSIYGAKLEKINEISTWNQRAEFREKEKKDLLSHYDTKIRIGNFNNIIENLSYQEVINGKGDVVVIYLLNREGRAIGIVYPNDDHKLLVRVETNIKFINKPCKNIAIPIHLEYQDESFRKDKYVDYSLTTTKKPNDPNKNAIPSNAPHVVLEEKKLSARRMFLEAGGSLRIQGHNNEDFLLKFYMTHLNPTGHSKDSFDKNYIQFMYLKGEEVLKDVEKKSASEFSVKYGQEEVERYFGAIDKYKETESFNFDYANSWKPYRSISDKFFDILKHCDNLNFMDGKKFTGNKYIKQIDESPNYYAMWKKSFFVKPLMKNPGPLLKYNIKEYNGNVDDKDIKQLCKAYKKDMIALYYKSGYRLITARYDTEKDKDWGGMFQPNQFYLKFKDKSYPKQTVYNRIADYIHDVKLLIDYALVFDGYFSEDRNTEKGEGFFAKIYNEFSKVSDLLDKMIAVVADNKKLSKELVFDADFLKESSGYVKYIEDVKQIIIEKLKEVVSLDADAYEQLQELSFSGIKKFSKRRDDEYKETVVAKKKLHIDDYEANWKDRIVNWEGFIRKSITSIAPGNKVFIGASSYEDFNKFLKELKKISSFIESNKNLTNRFVELVEEDSTYGRGYFSLSERDSLVQKYLPKFKPLKQKTKQNYLNIYENLGKIKEGSETVFGGIIANYVRIGEQTLVFNFFEGEFFDEVDYDSNLIKEKIEQVEHKDFIADVKEFIDMNSIYRTLNENICRFAISTSKAEESFMNERNRFFGTFATTFGNFSNVLAIEDKDDLFEPLITEIIDKKFLSKYGENGKFAKAIEKRLNIELNELEKNEKETRTKKRFLSIYNNLNKLKISHLVDNIFSLYYRDLLKKVGKYDEARKEDEVLLRKNDINEQTKG"

  num_samples: 10000
  batch_size: 128
  do_sample: true
  temperature: 1.0
  top_p: 0.5
  top_k: 0
  repetition_penalty: 1.05

- context:
    name: "crispr12a"
    seq: "2HKVSTQAYELWEKNSIAIKVKDLKEDEAKKFQGIAWLVKRAINYAGNADANKPLIANEQAEYNRSDYFIGDSNKVPSILFDVDTRGTISNRMQLMLSMLAMFSSYFAKDSQECLLARIDGQQYNIGYKNFLEKYASTLCVEEWDFVNNKKPNRFIRIRNGYSYLKWKKIYDADTRSFNKYDLAFEFLDEEPVYMIRDFSSIFKKSDAISTYKTKLLNVFGTSPDIKSTLWAPIYFIFGNQTSMSKFSEFKNTIQYGKLAGGTACPNSKKDVMYNLKDILMKEFKQYVQKEVKVRSNKFGSNLDELAIVADYKEVLECIKHVVQSIYGAKLEKINEISTWNQRAEFREKEKKDLLSHYDTKIRIGNFNNIIENLSYQEVINGKGDVVVIYLLNREGRAIGIVYPNDDHKLLVRVETNIKFINKPCKNIAIPIHLEYQDESFRKDKYVDYSLTTTKKPNDPNKNAIPSNAPHVVLEEKKLSARRMFLEAGGSLRIQGHNNEDFLLKFYMTHLNPTGHSKDSFDKNYIQFMYLKGEEVLKDVEKKSASEFSVKYGQEEVERYFGAIDKYKETESFNFDYANSWKPYRSISDKFFDILKHCDNLNFMDGKKFTGNKYIKQIDESPNYYAMWKKSFFVKPLMKNPGPLLKYNIKEYNGNVDDKDIKQLCKAYKKDMIALYYKSGYRLITARYDTEKDKDWGGMFQPNQFYLKFKDKSYPKQTVYNRIADYIHDVKLLIDYALVFDGYFSEDRNTEKGEGFFAKIYNEFSKVSDLLDKMIAVVADNKKLSKELVFDADFLKESSGYVKYIEDVKQIIIEKLKEVVSLDADAYEQLQELSFSGIKKFSKRRDDEYKETVVAKKKLHIDDYEANWKDRIVNWEGFIRKSITSIAPGNKVFIGASSYEDFNKFLKELKKISSFIESNKNLTNRFVELVEEDSTYGRGYFSLSERDSLVQKYLPKFKPLKQKTKQNYLNIYENLGKIKEGSETVFGGIIANYVRIGEQTLVFNFFEGEFFDEVDYDSNLIKEKIEQVEHKDFIADVKEFIDMNSIYRTLNENICRFAISTSKAEESFMNERNRFFGTFATTFGNFSNVLAIEDKDDLFEPLITEIIDKKFLSKYGENGKFAKAIEKRLNIELNELEKNEKETRTKKRFLSIYNNLNKLKISHLVDNIFSLYYRDLLKKVGKYDEARKEDEVLLRKNDINEQTKG"

  num_samples: 10000
  batch_size: 128
  do_sample: true
  temperature: 1.0
  top_p: 0.95
  top_k: 0
  repetition_penalty: 1.05
